language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm test
  - ./node_modules/.bin/istanbul cover _mocha --report lcovonly -- -R spec --recursive && cat ./coverage/lcov.info | ./node_modules/